### ISSUE TITLE
Add new initial setting for customizing a log package to be used by packageLog

### ISSUE THREAD

**Issue by poorejc** [apache/flagon-useralejs#35]
Might be nice if instead of requiring users to use our native log schema, users to specify their own in options API and use it with automated logging and custom logs. 

Imagine new field in options API. If is not null, then packageLog function uses some other object instead. May require exporting more functions for clientTime, etc., etc. to make it convenient for users to populate fields.

**Comment by Jyyjy** [comment]
I don't see why this can't be done with the existing package log callbacks. The callbacks are passed the log and a copy of the event, so a user could create a completely new log with the event. And a user could pick and choose from the log fields to get values like clientTime.

@poorejc if so can we close this issue. If not, what would be the added value of this added option?

**Comment by EandrewJones** [comment]
The custom logs theoretically support any schema the user wants. If using the package, not only can they define and enforce their own schema with their own code, they also can utilize any of the existing fields we provide as Jason notes.

Closing as completed for now since we do support the desired behavior.
